#!/usr/bin/env python3
"""EGC Suite - Antivirus Scanner Optimisé pour Linux"""
from src.antivirus.scanner import VirusScanner
from src.common.app import run_pyqt_app


def main():
    """Point d'entrée principal"""
    run_pyqt_app(VirusScanner)


if __name__ == "__main__":
    main()
