#!/usr/bin/env python3
"""EGC Suite - Amplificateur Audio Optimisé pour Linux"""
from src.audio.amplifier import SoundAmplifier
from src.common.app import run_pyqt_app


def main():
    """Point d'entrée principal"""
    run_pyqt_app(SoundAmplifier)


if __name__ == "__main__":
    main()
