#!/usr/bin/env python3
"""EGC Suite - Navigateur Web Optimisé pour Linux"""
from src.browser.navigator import OptimizedBrowser
from src.common.app import run_pyqt_app


def main():
    """Point d'entrée principal"""
    run_pyqt_app(OptimizedBrowser)


if __name__ == "__main__":
    main()
